[project]
name = "examples"
version = "0.1.0"
description = ""
authors = [
    {name = "joegasewicz",email = "joegasewicz@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "tornado (>=6.5.10,<7.0.0)",
    "marshmallow (>=4.3.1,<5.0.0)",
    "opencv-python (>=5.0.0.93,<6.0.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "ultralytics (>=8.4.174,<9.0.0)",
    "midv500 (>=0.2.1,<0.3.0)",
]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
